### ISSUE TITLE
Setup Continuous Integration on travis.ci for Linux

### ISSUE THREAD

**Issue by arecarn** [important-business/engine#5]

**Comment by KeeganMorrow** [comment]
I made some progress getting Travis set up based on what I'd done in my game_engine repo. I think we'll want to make quite a few changes (migrating to Ubuntu Trusty especially) though.

**Comment by arecarn** [comment]
This issue is too overarching I'm going to redcue it's scope to just  the Linux setup and create new issues for OSX and Windows

**Comment by arecarn** [comment]
created issues from this issue #19 #20 #21

**Comment by arecarn** [comment]
adding link to #21 since it's not working in last comment
