### ISSUE TITLE
Choice of Platform Library

### ISSUE THREAD

**Issue by arecarn** [important-business/engine#6]
(Impacted by supported platforms and languages)
SDL2 (Can also do rendering)
GLFW (Opens an OpenGL context)
PyGame (built on top of SDL2)
Other options?

**Comment by arecarn** [comment]
I'd say SDL2, over GLFW, but only because I've never heard of GLFW. Honestly I think this will take a little more research.

**Comment by KeeganMorrow** [comment]
I'm also leaning towards SDL2 at the moment. SDL has some basic graphics capabilities without actually using OpenGL, which GLFW does not. I want to look over the GLFW API a bit, but suspect that SDL2 is our best bet.

**Comment by arecarn** [comment]
SDL2 it is!
